name: Mirror Repo porfolio alain Piloto
on:
 push:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{secrets.TEST}}
jobs:
  mirror:
    runs-on: ubuntu-latest
    
    steps:
    - name: Mirror
      uses: repo-sync/github-sync@v2
      
      with:
        source_repo: alainpiloto/alainpiloto.github.io
        source_branch: main
        destination_branch: main

